# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created: Sun Nov 27 18:13:53 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    """
    View part of the MVC pattern
    """
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 247)
        Form.setMinimumSize(QtCore.QSize(630, 247))
        Form.setMaximumSize(QtCore.QSize(630, 247))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 61, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.offen_label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.offen_label.setFont(font)
        self.offen_label.setObjectName("offen_label")
        self.verticalLayout.addWidget(self.offen_label)
        self.korrekt_label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.korrekt_label.setFont(font)
        self.korrekt_label.setObjectName("korrekt_label")
        self.verticalLayout.addWidget(self.korrekt_label)
        self.falsch_label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.falsch_label.setFont(font)
        self.falsch_label.setObjectName("falsch_label")
        self.verticalLayout.addWidget(self.falsch_label)
        self.gesamt_label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.gesamt_label.setFont(font)
        self.gesamt_label.setObjectName("gesamt_label")
        self.verticalLayout.addWidget(self.gesamt_label)
        self.spiele_label = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.spiele_label.setFont(font)
        self.spiele_label.setObjectName("spiele_label")
        self.verticalLayout.addWidget(self.spiele_label)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 10, 71, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.offen_value_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.offen_value_label.setText("")
        self.offen_value_label.setObjectName("offen_value_label")
        self.verticalLayout_2.addWidget(self.offen_value_label)
        self.korrekt_value_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.korrekt_value_label.setText("")
        self.korrekt_value_label.setObjectName("korrekt_value_label")
        self.verticalLayout_2.addWidget(self.korrekt_value_label)
        self.falsch_value_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.falsch_value_label.setText("")
        self.falsch_value_label.setObjectName("falsch_value_label")
        self.verticalLayout_2.addWidget(self.falsch_value_label)
        self.gesamt_value_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.gesamt_value_label.setText("")
        self.gesamt_value_label.setObjectName("gesamt_value_label")
        self.verticalLayout_2.addWidget(self.gesamt_value_label)
        self.spiele_value_label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.spiele_value_label.setText("")
        self.spiele_value_label.setObjectName("spiele_value_label")
        self.verticalLayout_2.addWidget(self.spiele_value_label)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 60, 481, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 30, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.neu_button = QtGui.QPushButton(Form)
        self.neu_button.setGeometry(QtCore.QRect(240, 200, 91, 23))
        self.neu_button.setObjectName("neu_button")
        self.ende_button = QtGui.QPushButton(Form)
        self.ende_button.setGeometry(QtCore.QRect(430, 200, 91, 23))
        self.ende_button.setObjectName("ende_button")

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.ende_button, QtCore.SIGNAL("clicked()"), Form.close)
        QtCore.QObject.connect(self.neu_button, QtCore.SIGNAL("clicked()"), Form.set_up)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Qt Game", None, QtGui.QApplication.UnicodeUTF8))
        self.offen_label.setText(QtGui.QApplication.translate("Form", "Offen:", None, QtGui.QApplication.UnicodeUTF8))
        self.korrekt_label.setText(QtGui.QApplication.translate("Form", "Korrekt:", None, QtGui.QApplication.UnicodeUTF8))
        self.falsch_label.setText(QtGui.QApplication.translate("Form", "Falsch:", None, QtGui.QApplication.UnicodeUTF8))
        self.gesamt_label.setText(QtGui.QApplication.translate("Form", "Gesamt:", None, QtGui.QApplication.UnicodeUTF8))
        self.spiele_label.setText(QtGui.QApplication.translate("Form", "Spiele:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Drücken Sie die Buttons in aufsteigender Reihenfolge", None, QtGui.QApplication.UnicodeUTF8))
        self.neu_button.setText(QtGui.QApplication.translate("Form", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.ende_button.setText(QtGui.QApplication.translate("Form", "Ende", None, QtGui.QApplication.UnicodeUTF8))

